### PR TITLE
Bump avif-serialize version to 0.7.4

### PR DESCRIPTION
**Pull request by wantehchang**

### CODE REVIEW

**Comment by wantehchang** [comment]
@kornelski Please take a look. If it is better to leave the avif-serialize version at 0.7.2, please feel free to decline this pull request. Thank you.

**Comment by kornelski** [comment]
Cargo doesn't use the versions specified in Cargo.toml, so this change is unnecessary.

**Comment by wantehchang** [comment]
Thanks for the quick reply. Should I abandon this pull request?

I am not familiar with Cargo. My testing showed that Cargo appears to use a version that is greater than or equal to the version specified in Cargo.toml. For example, if I change that line to:

`avif-serialize = "0.7.5"`

Then `cargo build` fails:

```
$ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `avif-serialize = "^0.7.5"`
candidate versions found which didn't match: 0.7.4, 0.7.3, 0.7.2, ...
location searched: crates.io index
required by package `ravif v0.8.5 (/usr/local/google/home/wtc/cavif-rs.1/cavif-rs/ravif)`
    ... which is depended on by `cavif v1.3.1 (/usr/local/google/home/wtc/cavif-rs.1/cavif-rs)`
```

So this change seems to cause Cargo to require avif-serialize 0.7.4 as I intended.

**Comment by wantehchang** [comment]
I abandoned this pull request.

**Pull request closed without merging**
